### ISSUE TITLE
api support from level 21

### ISSUE THREAD

**Issue by calidion** [CircleCI-Public/cimg-android#63]
level 27 is too high for some projects needs compatibility and vast range support.

**Comment by JalexChen** [comment]
hi @calidion - level 21 was never supported by this image since it is extremely outdated and well below the minimum level for most development. we have actually removed levels 23-26 due to the same reasons and in wanting to keep the image small for a better experience overall.

for your use case of using 21, it might be better to use our template and/or make a custom image that satisfies your needs.
