### ISSUE TITLE
Node 18 Image?

### ISSUE THREAD

**Issue by marco-elder** [CircleCI-Public/cimg-android#66]
Hi guys, thanks for providing these images! The ones that include Node are really useful in our workflow.

Is there any chance that we could get the images containing Node 18 (LTS since October) soon? I think https://github.com/CircleCI-Public/cimg-android/pull/61 should have created them on merge, but [the build was cancelled](https://app.circleci.com/pipelines/github/CircleCI-Public/cimg-android/181/workflows/61be273c-d8dd-4f08-ae6e-6cb9d6d1e4af/jobs/183) for some reason.

Cheers!

**Comment by JalexChen** [comment]
hi @marco-elder - you're right. looks like this was cancelled for some reason. I don't recall specifically why, but i believe it's because there was no corresponding machine image update; we have held off on a couple of these, but we're looking into resuming the updates shortly. the 2022.10 directory will likely be removed and instead have a 2022.12 tag.

**Comment by marco-elder** [comment]
I see, thank you for the reply @JalexChen We'll wait for the 2022.12 tag.
