### ISSUE TITLE
Use specific java versions?

### ISSUE THREAD

**Issue by dessalines** [CircleCI-Public/cimg-android#70]
A linting plugin https://github.com/jeremymailen/kotlinter-gradle , requires java 17 to run. That means I can't use this image to run lints anymore.

**Comment by JalexChen** [comment]
At the moment, it doesn't seem like full support is available for Java 17 - it might just be Android Studio and that is through an embedded jdk. We'll keep an eye on this as more information surfaces. Putting this in the backlog for now.

**Comment by dessalines** [comment]
Thanks. For info, my log error for weeks has been:

```
* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
      Your current JDK is located in /usr/lib/jvm/java-11-openjdk-amd64
      You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

**Comment by laenger** [comment]
https://developer.android.com/studio/preview/features/#jdk-17-agp
> When using Android Gradle Plugin 8.0 to build your app, JDK 17 is now required to run Gradle.

**Comment by Mygod** [comment]
This should be supported since the next AGP has already hit beta...

**Comment by JalexChen** [comment]
hi @laenger and @Mygod - we're looking into this and will have an update weds 3/8 if not sooner. I think it's the correct call to include java 17, especially since it's the latest LTS version, AGP 8.0 requires it, and it coincides with official support from android in the latest developer version, which will be packaged in the next release.

my previous comment was specifically targeted towards android studio, which does include java 17 embedded. however, this is not an android studio image.

while i understand it can also be an extra step, installing the `openjdk-17-jdk` package or using the [android-orb](https://circleci.com/developer/orbs/orb/circleci/android) to change java's version might be an alternative until then.

thanks for being patient with us.

**Comment by Mygod** [comment]
Still no release?

**Comment by ryanbourdais** [comment]
Hi @Mygod I am currently working on the machine executor release as well, once that is done I will publish both so that there is parity between the 2 options.

**Comment by ryanbourdais** [comment]
@Mygod @dessalines I have released the new docker image today as `cimg/android:2023.03.1` and the machine executor has been released as `android:edge` for the time being. Both of these releases feature replacing Java 11 with Java 17

**Comment by dessalines** [comment]
Thanks!

**Comment by dessalines** [comment]
edit: Now I'm getting permissions errors with this new image:

> Failed to create parent directory '/.../.gradle' when creating directory '/.../.gradle/vcs-1'

**Comment by dessalines** [comment]
I haven't found one unfortunately. I'm currently only doing formatting checks in my CI, not building images anymore.

**Comment by agustinsivoplas** [comment]
Same issue happens with cimg/android:2023.04.1
